# Dockerfile for AquaPos (Vite React App)
FROM node:20-alpine as build

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
ARG VITE_APPWRITE_ENDPOINT
ARG VITE_APPWRITE_PROJECT_ID
ARG VITE_APPWRITE_DATABASE_ID
ARG VITE_APPWRITE_COLLECTION_INVENTORY_ID
ARG VITE_APPWRITE_COLLECTION_SALES_ID
ARG VITE_APPWRITE_FUNCTION_PROCESS_SALE_ID
ARG VITE_APPWRITE_COLLECTION_CUSTOMERS_ID
ARG VITE_APPWRITE_COLLECTION_SUPPLIERS_ID
ARG VITE_APPWRITE_COLLECTION_ORDERS_ID
ARG VITE_APPWRITE_FUNCTION_RECEIVE_STOCK_ID
ARG GEMINI_API_KEY

ENV VITE_APPWRITE_ENDPOINT=$VITE_APPWRITE_ENDPOINT
ENV VITE_APPWRITE_PROJECT_ID=$VITE_APPWRITE_PROJECT_ID
ENV VITE_APPWRITE_DATABASE_ID=$VITE_APPWRITE_DATABASE_ID
ENV VITE_APPWRITE_COLLECTION_INVENTORY_ID=$VITE_APPWRITE_COLLECTION_INVENTORY_ID
ENV VITE_APPWRITE_COLLECTION_SALES_ID=$VITE_APPWRITE_COLLECTION_SALES_ID
ENV VITE_APPWRITE_FUNCTION_PROCESS_SALE_ID=$VITE_APPWRITE_FUNCTION_PROCESS_SALE_ID
ENV VITE_APPWRITE_COLLECTION_CUSTOMERS_ID=$VITE_APPWRITE_COLLECTION_CUSTOMERS_ID
ENV VITE_APPWRITE_COLLECTION_SUPPLIERS_ID=$VITE_APPWRITE_COLLECTION_SUPPLIERS_ID
ENV VITE_APPWRITE_COLLECTION_ORDERS_ID=$VITE_APPWRITE_COLLECTION_ORDERS_ID
ENV VITE_APPWRITE_FUNCTION_RECEIVE_STOCK_ID=$VITE_APPWRITE_FUNCTION_RECEIVE_STOCK_ID
ENV GEMINI_API_KEY=$GEMINI_API_KEY

RUN npm run build

# Use Nginx to serve the static files
FROM nginx:stable-alpine
COPY --from=build /app/dist /usr/share/nginx/html
# Copy a custom nginx config if needed for SPA routing
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
